# Generated by Django 4.1.5 on 2023-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_historicalcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='Course price '),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Course duration in month '),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='Course price '),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Course duration in month '),
        ),
    ]
