# Generated by Django 4.1.5 on 2023-01-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_age',
            field=models.IntegerField(verbose_name='Techer work age: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='User age: '),
        ),
    ]
