# Generated by Django 4.1.5 on 2023-01-19 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title'),
        ('authentication', '0002_alter_teacher_work_age_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_id',
            field=models.ManyToManyField(related_name='user_courses', to='courses.course', verbose_name='User courses '),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User id '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses_id',
            field=models.ManyToManyField(related_name='teacher_courses', to='courses.course', verbose_name='Teacher courses '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User id '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_age',
            field=models.IntegerField(verbose_name='Techer work age '),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='User age '),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='User email '),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name '),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name '),
        ),
    ]
