# Generated by Django 4.1.5 on 2023-01-19 23:02

import web_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_student_courses_id_alter_student_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[web_project.validators.correct_age_value], verbose_name='User age '),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[web_project.validators.correct_string_length], verbose_name='First name '),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[web_project.validators.correct_string_length], verbose_name='Last name '),
        ),
    ]
