# Generated by Django 4.1.5 on 2023-01-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title'),
        ('authentication', '0004_alter_user_age_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id', 'email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('HR', 'Teacher'), ('CA', 'Student')], default='CA', max_length=255, verbose_name='USer role '),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_id',
            field=models.ManyToManyField(blank=True, related_name='user_courses', to='courses.course', verbose_name='User courses '),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User email '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses_id',
            field=models.ManyToManyField(blank=True, related_name='teacher_courses', to='courses.course', verbose_name='Teacher courses '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User email '),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='User age '),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name '),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name '),
        ),
    ]
