# Generated by Django 4.1.5 on 2023-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_age',
            field=models.IntegerField(null=True, verbose_name='Techer work age '),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('HR', 'Teacher'), ('CA', 'Student')], default='CA', max_length=255, null=True, verbose_name='User role '),
        ),
    ]
